# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-16 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160716_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predefinedservice',
            name='description',
            field=models.TextField(default='Add a description.'),
        ),
        migrations.AlterField(
            model_name='predefinedservice',
            name='title',
            field=models.CharField(default='untitled', max_length=100),
        ),
    ]
