# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-16 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160716_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predefinedservice',
            name='description',
            field=models.TextField(blank=True, default='Add a description.', null=True),
        ),
        migrations.AlterField(
            model_name='predefinedservice',
            name='title',
            field=models.CharField(blank=True, default='untitled', max_length=100, null=True),
        ),
    ]
