# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-17 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20160716_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='predefinedservice',
            name='images',
            field=models.ImageField(null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='predefinedservice',
            name='price',
            field=models.FloatField(default='0.000'),
        ),
    ]
