# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-17 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20160717_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predefinedservice',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
