# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-17 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20160717_0537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predefinedservice',
            name='images',
        ),
        migrations.AddField(
            model_name='predefinedservice',
            name='image',
            field=models.ImageField(null=True, upload_to='predefined'),
        ),
    ]
