# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-06 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20160719_0652'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='predefined')),
            ],
        ),
        migrations.RemoveField(
            model_name='predefinedservice',
            name='image',
        ),
        migrations.AddField(
            model_name='predefinedservice',
            name='images',
            field=models.ManyToManyField(to='app.ServiceImage'),
        ),
    ]
