# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-11 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20160806_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predefinedservice',
            name='images',
        ),
        migrations.AddField(
            model_name='predefinedservice',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ServiceImage'),
        ),
    ]
