# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-13 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20160811_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceimage',
            name='name',
            field=models.CharField(max_length=9001, null=True),
        ),
    ]
