# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-14 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_providerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predefinedservice',
            name='images',
        ),
        migrations.AddField(
            model_name='predefinedservice',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ServiceImage',
        ),
    ]
