# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-14 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20160814_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField(null=True)),
                ('name', models.CharField(max_length=9001, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='predefinedservice',
            name='image',
        ),
        migrations.AddField(
            model_name='predefinedservice',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ServiceImage'),
        ),
    ]
