# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-14 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20160814_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceimage',
            name='image',
            field=models.ImageField(null=True, upload_to='predefined'),
        ),
    ]
