# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-15 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20160814_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predefinedservice',
            name='images',
        ),
        migrations.AddField(
            model_name='serviceimage',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.PredefinedService'),
        ),
    ]
