# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-15 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20160815_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceimage',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
