# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-17 06:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20160815_0926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceimage',
            old_name='service',
            new_name='predefinedservice',
        ),
    ]
