# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-04 08:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20160902_1428'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PredefinedService',
            new_name='OfferedService',
        ),
        migrations.RenameField(
            model_name='serviceimage',
            old_name='predefinedservice',
            new_name='offeredservice',
        ),
    ]
