# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-04 08:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20160904_0849'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProviderProfile',
            new_name='Profile',
        ),
    ]
