# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-04 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20160904_0854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='untitled', max_length=100, null=True)),
                ('description', models.TextField(default='No description available.')),
                ('price', models.FloatField(default=0.0)),
                ('status', models.CharField(blank=True, default='pending', max_length=100, null=True)),
                ('due_date', models.DateTimeField()),
                ('created_date', models.DateTimeField()),
                ('seeker', models.IntegerField()),
                ('provider', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='offeredservice',
            name='description',
        ),
        migrations.RemoveField(
            model_name='offeredservice',
            name='price',
        ),
        migrations.RemoveField(
            model_name='offeredservice',
            name='title',
        ),
        migrations.RemoveField(
            model_name='serviceimage',
            name='offeredservice',
        ),
        migrations.AddField(
            model_name='offeredservice',
            name='category',
            field=models.CharField(default='other', max_length=1337),
        ),
        migrations.AddField(
            model_name='offeredservice',
            name='service',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Service'),
        ),
        migrations.AddField(
            model_name='serviceimage',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Service'),
        ),
    ]
