# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-04 10:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20160904_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='provider',
            new_name='providerpk',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='seeker',
            new_name='seekerpk',
        ),
    ]
