# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-04 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_remove_profile_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.IntegerField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='PublicService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='other', max_length=1337)),
                ('service', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Service')),
            ],
        ),
        migrations.AddField(
            model_name='bid',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PublicService'),
        ),
    ]
