# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-04 12:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20160904_1207'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='_Service',
        ),
    ]
