# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-04 12:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20160904_1209'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='_Service',
            new_name='Service',
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.OfferedService'),
        ),
    ]
