# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-04 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20160904_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Service')),
            ],
        ),
    ]
