# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-05 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20160905_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
