# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-05 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20160905_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='providerpk',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='seekerpk',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
