# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-15 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20160905_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='usertype',
            field=models.CharField(default='seeker', max_length=101),
        ),
    ]
